### ISSUE TITLE
a11y audit fixes

### ISSUE THREAD

**Issue by carylwyatt** [hathitrust/firebird-common#69]
🚨 means critical issue

## overall style issues
- [ ] lack of proper focus contrast on buttons, lack of proper contrast on cookie banner links
- [ ] [1727428](https://axeauditor.dequecloud.com/test-run/b2613a94-fe0b-11ee-96ce-dfcb37e53e3c/issue/52dfb086-fe34-11ee-8af8-d30071727c2a?sortField=ordinal&sortDir=asc&filter%5Bpage_number%5D=6&row=0) the "visual boundary" or outline of form fields (radio button, checkboxes, etc.) lack proper contrast 
  - [ ] [1727509](https://axeauditor.dequecloud.com/test-run/b2613a94-fe0b-11ee-96ce-dfcb37e53e3c/issue/08f3a3f0-fe3f-11ee-b17f-9b79db14f688?sortField=severity&sortDir=desc&page=0&issuesCount=&row=0&filter%5Bpage_number%5D=0) shows up in search results checkboxes, too
  - [ ] if we increase the bootstrap elements border `rgba` value from `(0,0,0,0.25)` to `(0,0,0,0.45)` this gets cleared up for checkboxes and radio buttons

### Critical issues - [DEV-1165] 
- [ ] https://github.com/hathitrust/firebird-common/issues/71
-  🚨 [1727510](https://axeauditor.dequecloud.com/test-run/b2613a94-fe0b-11ee-96ce-dfcb37e53e3c/issue/136cd630-fe3f-11ee-b5ef-37a650e942e8?sortField=ordinal&sortDir=asc&filter%5Bpage_number%5D=6&row=0) radio button does not have role and/or state
-  🚨 [1727483](https://axeauditor.dequecloud.com/test-run/b2613a94-fe0b-11ee-96ce-dfcb37e53e3c/issue/848ccb44-fe3b-11ee-8829-bbb441666957?activeTab=dt-issue&page=0&pageSize=100&sortField=ordinal&sortDir=asc&row=0&searchKeyword=1727483&searchOn=id) focus indicator missing on select language and select format 
### Regular priority - [DEV-1175]
- [ ] [1727490](https://axeauditor.dequecloud.com/test-run/b2613a94-fe0b-11ee-96ce-dfcb37e53e3c/issue/d0e6d2b8-fe3c-11ee-9b95-afef09a9ba8b?activeTab=dt-issue&page=0&pageSize=100&sortField=ordinal&sortDir=asc&row=0&searchKeyword=1727490&searchOn=id) label on search field is not persistent
- [ ] [1727489](https://axeauditor.dequecloud.com/test-run/b2613a94-fe0b-11ee-96ce-dfcb37e53e3c/issue/a2643b74-fe3c-11ee-999f-8347c5505710?sortField=ordinal&sortDir=asc&filter%5Bpage_number%5D=6&row=0) dropdown fields don't have informative labels
- [ ] [1727499](https://axeauditor.dequecloud.com/test-run/b2613a94-fe0b-11ee-96ce-dfcb37e53e3c/issue/1cbfa3da-fe3e-11ee-a1dd-3b59689c7f4e?sortField=ordinal&sortDir=asc&filter%5Bpage_number%5D=6&row=0) when screen is 320px, you lose the number in the "search term" placeholder text
- [ ] [1728295](https://axeauditor.dequecloud.com/test-run/b2613a94-fe0b-11ee-96ce-dfcb37e53e3c/issue/cfa45d66-0063-11ef-93bf-030c24af5dbd?sortField=ordinal&sortDir=asc&filter%5Bpage_number%5D=6&row=0) select language/select format contrast issues once selected

## navbar - [DEV-1174]

- [ ] [1727975](https://axeauditor.dequecloud.com/test-run/b2613a94-fe0b-11ee-96ce-dfcb37e53e3c/issue/0cb64ae0-ff1d-11ee-934f-6ff1ae8d2d9c?sortField=severity&sortDir=desc&page=0&issuesCount=&filter%5Bcomponent_number%5D=1&row=3) focus indicator lacks contrast
- [ ] [1727026](https://axeauditor.dequecloud.com/test-run/b2613a94-fe0b-11ee-96ce-dfcb37e53e3c/issue/302de104-fe0f-11ee-ac5b-ff3565d28288?sortField=severity&sortDir=desc&page=0&issuesCount=&filter%5Bcomponent_number%5D=1&row=5) expand/collapse on search bar isn't setting aria expanded correctly

## search bar - [DEV-1176]
- [ ] [1727130](https://axeauditor.dequecloud.com/test-run/b2613a94-fe0b-11ee-96ce-dfcb37e53e3c/issue/5f666b18-fe13-11ee-9637-bf024df4c4f2?viewMode=issues&sortField=ordinal&sortDir=asc&filter%5Bcomponent_number%5D=3&row=0) the search bar dropdown filters don't have "visible labels" (but they _do_ have aria-labels)

### Critical issues - [DEV-1165]
- [ ] 🚨 [1727249](https://axeauditor.dequecloud.com/test-run/b2613a94-fe0b-11ee-96ce-dfcb37e53e3c/issue/6a697dd4-fe27-11ee-bc1f-9f18b5e39269?sortField=severity&sortDir=desc&page=0&issuesCount=&filter%5Bcomponent_number%5D=1&row=0) green check mark validation on form fields lacking alternate text
### Regular priority - [DEV-1177]
- [ ] [1727230](https://axeauditor.dequecloud.com/test-run/b2613a94-fe0b-11ee-96ce-dfcb37e53e3c/issue/c5c9a642-fe25-11ee-a00b-d7cff31345ee?sortField=severity&sortDir=desc&page=0&issuesCount=&filter%5Bcomponent_number%5D=1&row=1) identify input purpose missing for name and email
- [ ] [1727976](https://axeauditor.dequecloud.com/test-run/b2613a94-fe0b-11ee-96ce-dfcb37e53e3c/issue/640c95ec-ff1d-11ee-a7da-77df04ada542?sortField=severity&sortDir=desc&page=0&issuesCount=&filter%5Bcomponent_number%5D=1&row=2) form validation error messages lack contrast
- [ ] [1727235](https://axeauditor.dequecloud.com/test-run/b2613a94-fe0b-11ee-96ce-dfcb37e53e3c/issue/d5e1e160-fe26-11ee-8084-d3b22a82817e?sortField=severity&sortDir=desc&page=0&issuesCount=&filter%5Bcomponent_number%5D=1&row=6) form validation error messages not being announced by screen reader
- [ ] [1727229](https://axeauditor.dequecloud.com/test-run/b2613a94-fe0b-11ee-96ce-dfcb37e53e3c/issue/81c6ae40-fe25-11ee-aa61-97d2fe293477?sortField=severity&sortDir=desc&page=0&issuesCount=&filter%5Bcomponent_number%5D=1&row=4) when modal is closed, focus isn't returned to trigger

## tables - [DEV-1178]
- [ ] [1727031](https://axeauditor.dequecloud.com/test-run/b2613a94-fe0b-11ee-96ce-dfcb37e53e3c/issue/9e2b96a6-fe0f-11ee-b670-4f79e119b55e?activeTab=issues-list&page=0&sortField=ordinal&sortDir=asc&issuesCount=&filter%5Bpage_number%5D=1&pageSize=10&xhr=true&_=1715025488816) color contrast of orange link text in table against gray background (my guess is both the gray and the orange need to be changed 😬 )  _**70+ issues related to this**_

## "design" components - [DEV-1179]
- [ ] [1727518](https://axeauditor.dequecloud.com/test-run/b2613a94-fe0b-11ee-96ce-dfcb37e53e3c/issue/5ed7f8f2-fe3f-11ee-8326-b71c7e04ea6a?sortField=severity&sortDir=desc&page=0&issuesCount=&row=5&filter%5Bpage_number%5D=0) hathi-collections-toolbar "select all items" checkbox button doesn't have a "pressed/unpressed" state conveyed to screen reader users
  - [ ] [1728277](https://axeauditor.dequecloud.com/test-run/b2613a94-fe0b-11ee-96ce-dfcb37e53e3c/issue/0a3e3cbc-005a-11ef-8764-cf40999bf5e1?viewMode=issues&sortField=ordinal&sortDir=asc&row=0&filter%5Bpage_number%5D=5) same component, different app
- [ ] [1728595](https://axeauditor.dequecloud.com/test-run/b2613a94-fe0b-11ee-96ce-dfcb37e53e3c/issue/894525ee-0086-11ef-a8dd-db78ee811ab9?viewMode=issues&sortField=ordinal&sortDir=asc&filter%5Bcomponent_number%5D=6&row=1) in [CollectionEditModal](https://github.com/hathitrust/firebird-common/blob/958b4c711ddd4e226d3b4e678ef9adb74d27f80e/src/js/components/CollectionEditModal/index.svelte#L98-L113): "collection visible to others" group of radio buttons is missing fieldset
  - problem: the label associated with the radio button(s) is a paragraph tag instead of a "legend"

[DEV-1174]: https://hathitrust.atlassian.net/browse/DEV-1174?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DEV-1165]: https://hathitrust.atlassian.net/browse/DEV-1165?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DEV-1175]: https://hathitrust.atlassian.net/browse/DEV-1175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by angelinanz** [comment]
I broke the major issues above into separate issues.
